apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  namespace: workshop
spec:
  type: LoadBalancer
  selector:
    role: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000