name: Build and Deploy to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'k8s_manifests/**'
      - '.github/workflows/**'

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Login to ACR
      run: az acr login --name threetieracr2025mp
    
    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/backend:${{ github.sha }} ./app/backend
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/backend:latest ./app/backend
        docker push ${{ env.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/backend:latest
    
    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} ./app/frontend
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest ./app/frontend
        docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:latest
    
    - name: Set AKS Context
      run: az aks get-credentials --resource-group ${{ env.AKS_RESOURCE_GROUP }} --name ${{ env.AKS_CLUSTER_NAME }}
    
    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s_manifests/mongo/secrets.yaml
        kubectl apply -f k8s_manifests/mongo/deploy.yaml
        kubectl apply -f k8s_manifests/mongo/service.yaml
        kubectl apply -f k8s_manifests/backend-deployment.yaml
        kubectl apply -f k8s_manifests/backend-service.yaml
        kubectl apply -f k8s_manifests/frontend-deployment.yaml
        kubectl apply -f k8s_manifests/frontend-service.yaml
        kubectl apply -f k8s_manifests/full_stack_lb.yaml
    
    - name: Verify Deployment
      run: |
        kubectl get pods -n workshop
        kubectl get svc -n workshop